# Rename this app before your first deploy, for example:
# fly apps create tele-consult
# Then update the app value below.
app = "tele-consult"
primary_region = "sin"

[env]
  PORT = "3001"

[experimental]
  cmd = ["sh", "-c", "pnpm db:push && node dist/main"]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
